trigger:
- Develop

resources:
- repo: self

pool:
  name: 'Default'
  demands:
  - agent.name -equals agentclass2

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build_api
    displayName: Build api
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'classtrackapi'
        command: 'build'
        Dockerfile: '**/backend/Dockerfile'
        arguments: '-t classtrackapi.azurecr.io/classtrack-api:latest'
    
    - task: Docker@2
      inputs:
        containerRegistry: 'classtrackapi'
        repository: 'classtrackapi.azurecr.io/classtrack-api'
        command: 'push'
        tags: 'latest'

  - job: Build
    displayName: Build front
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'classtrackapi'
        command: 'build'
        Dockerfile: '**/ClassTrack/Dockerfile'
        arguments: '-t classtrackapi.azurecr.io/classtrack-front:latest'
    - task: Docker@2
      inputs:
        containerRegistry: 'classtrackapi'
        repository: 'classtrackapi.azurecr.io/classtrack-front'
        command: 'push'
        tags: 'latest'

- stage: Deploy
  displayName: Deploy to Azure Web
  dependsOn: Build
  jobs:
  - job: Deploy_api
    displayName: Deploy api
    steps:    
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Azure for Students(8c757b97-b103-445f-9aa8-d6cff021ddcf)'
        appName: 'ClassTrack-API-Alumnos2'
        containers: 'classtrackapi.azurecr.io/classtrack-api:latest'
        appSettings: '-Port 3000'
  - job: Deploy
    displayName: Deploy
    steps:    
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Azure for Students(8c757b97-b103-445f-9aa8-d6cff021ddcf)'
        appName: 'ClassTrack-Frontend'
        containers: ' classtrackapi.azurecr.io/classtrack-front:latest'
        appSettings: '-Port 8081 -RequestTimeout 6000'