
trigger:
- feature/Docker

resources:
- repo: self

pool:
  name: 'Default'
  demands:
  - agent.name -equals agentclass

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build and push Docker image
      inputs:
        containerRegistry: 'classtrackapi'
        command: 'build'
        Dockerfile: '**/backend/Dockerfile'
        arguments: '-t classtrackapi.azurecr.io/classtrack-api:latest'
  