trigger:
- feature/Docker

resources:
- repo: self

pool:
  name: 'Default'
  demands:
  - agent.name -equals agentclass2

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        containerRegistry: 'classtrackapi'
        command: 'build'
        Dockerfile: '**/backend/Dockerfile'
        arguments: '-t classtrackapi.azurecr.io/classtrack-api:latest'
    - task: Docker@2
      displayName: Push Docker image
      inputs:
        containerRegistry: 'classtrackapi'
        command: 'push'
        repository: 'classtrack-api'
        tags: 'latest'
    - task: AzureWebAppContainer@1
      displayName: Deploy Docker image to Azure Web App
      inputs:
        azureSubscription: 'Azure for Students(8c757b97-b103-445f-9aa8-d6cff021ddcf)'
        appName: 'ClassTrack-API-Alumnos'
        containers: 'classtrackapi.azurecr.io/classtrack-api:latest'
        appSettings: '-Port 3000'